services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: djangoia
      POSTGRES_PASSWORD: ia2025
      POSTGRES_DB: appia
    ports:
      - "5432:5432" # Solo para desarrollo, remover en producción
    networks:
      - app-network
    container_name: db # Añadimos un nombre de contenedor para mayor claridad

  model_app:
    build:
      context: ./iamodel
      dockerfile: Dockerfile.model
    ports:
      - "5000:5000"
    volumes:
      - ./core/best_mnist_model.h5:/app/model/best_mnist_model.h5
      - ./model:/app/model
    networks:
      - app-network
    container_name: iaapi

  web:
    build:
      context: .\iaapplication
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: djangoia
      POSTGRES_PASSWORD: ia2025
      POSTGRES_DB: appia
      DB_HOST: db # Usamos el nombre del servicio 'db'
      DB_PORT: 5432
      MODEL_API_URL: http://model_app:5000/predict # Asegúrate de que coincida
    depends_on:
      - db
      # - model_app
    networks:
      - app-network
    container_name: web

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:


  # DATABASE_URL: postgres://djangoia:ia2025@db:5432/appia