# Generated by Django 5.2 on 2025-04-24 14:15

import prediciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predicciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=prediciones.models.subirImagen)),
                ('prediccion', models.IntegerField(blank=True, null=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Predicciones',
            },
        ),
    ]
