# Generated by Django 5.2 on 2025-04-24 17:33

import prediciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicciones',
            name='imagen_preprocesada',
            field=models.ImageField(blank=True, null=True, upload_to=prediciones.models.subirImagen),
        ),
    ]
